name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2
      - name: Unit Tests
        run: .script/test
      - name: Build and Test
        run: ./script/test-build
