name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  CI:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2
      - name: Unit Tests
        run: ./script/test

      - name: Run End-to-End Tests for ${{matrix.goos}}/${{matrix.goarch}}
        run: ./script/test-build-ci ${{matrix.goos}} ${{matrix.goarch}}
