name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  CI:
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2
      - name: Unit Tests
        run: ./script/test
      - name: Build
        run: GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -o bin/actions-sync main.go
      - name: Build and Test
        run: ./script/test-build
